### ISSUE TITLE
UI Change: change the hover effect of the shortener button

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#172]
### Description

Hey guys,

We would like to change the hover effect of the shortener button.
The effect color are too different and we believe we can do much better.

### Screenshots

<img width="329" alt="image" src="https://user-images.githubusercontent.com/48911144/195178760-9eabd49a-d593-4804-9cb7-ac1d09000f45.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/48911144/195178816-237cc49d-bd98-4cdf-9d27-8a38c254162c.png">

**Comment by lauk20** [comment]
Hi, can I be assigned to this?

**Comment by origranot** [comment]
> Hi, can I be assigned to this?

Yea, go ahead!

**Comment by cweave** [comment]
Should've commented it and didn't refresh before assignment 🤐 I played around and made some style changes. 

Disabled:
![image](https://user-images.githubusercontent.com/16121690/195242354-63766197-6685-4d56-9cfd-5adf08f9a369.png)

Available:
![image](https://user-images.githubusercontent.com/16121690/195242459-08061a54-a37e-41f0-a0d6-790622bf86d8.png)

Hover/Active:
![image](https://user-images.githubusercontent.com/16121690/195242639-e3eb2c6d-6a3b-4bcb-ba4d-35680c8e8e43.png)

I'll let lauk20 have their stab at it since they called dibs before I submit anything, just thought I'd share :)

**Comment by lauk20** [comment]
Thanks! I have submitted a pull request to address this issue. It changes some of the form input styling and button styling too.

**Comment by GuillemPM** [comment]
I'm sorry guys, I'll close this issue since we completely changed the UI :( I hope you will help on any other issue ♥
