### ISSUE TITLE
Two or more seperate reduced URLs and for the same URL

### ISSUE THREAD

**Issue by TanmayPatil105** [origranot/reduced.to#299]
### Description

The site generates two seperate URLs for the same URL which adds to redundancy. In long run, this would lead to a big problem.

`How to reproduce?`

The following two reduced URLs redirect to the same URL and were generated couple of seconds apart.
1. [Link1](https://reduced.to/kaz6t)
2. [Link2](https://reduced.to/53b4u)

So to avoid this, a cache database can be implemented which stores the URL and the shortened URL, `refreshes` after certain amount of time.

**Comment by GuillemPM** [comment]
Hello @TanmayPatil105,

This is working as expected, since every url should be individual and will have its own tracking statistics, even if they point to the same url.

What we could do is implement some kind of link reference between shortened and long urls, to not store duplicate data.
So how is it working now:

Our cache database is storing the following:
```
https://reduced.to/kaz6t -> https://twitter.com/home
https://reduced.to/53b4u -> https://twitter.com/home
...
```

Maybe would be interesting to use some sorte of ref like this:
```
Cache short db:
https://reduced.to/kaz6t -> ref1
https://reduced.to/53b4u -> ref1

Cache ref db:
ref1 -> https://twitter.com/home
```

So if there are 100 shortened urls pointing to the same long url, they will all use the same ref which will save a huge amount of space, but I'm not sure about performance.

**Comment by TanmayPatil105** [comment]
Yess, We can't have best of both worlds. The `ref` thing looks better to me. Maintaining a small `cache ref` wouldn't affect performance much and would save a lot of space. In future, if there a feature to login, then for a specific user you can maintain a small cache the way I mentioned. Just my thoughts!!

**Comment by GuillemPM** [comment]
Sure! The thing is that actually the cache is being used for fast redirects, so there is no information about the user.
After we implement next features we can start thinking about this, I will keep the issue open
